DROP TABLE IF EXISTS DRIVER_STANDINGS CASCADE;
DROP TABLE IF EXISTS RACES CASCADE;
DROP TABLE IF EXISTS CIRCUITS CASCADE;

CREATE TABLE CIRCUITS(
circuitid INT NOT NULL,
alt INT NOT NULL,
PRIMARY KEY(circuitid));
COPY CIRCUITS FROM 'C:\uni\8x\ATD\archive\circuits_modified.csv' DELIMITER ',' CSV HEADER;

CREATE TABLE RACES (
raceid INT NOT NULL,
circuitid INT NOT NULL,
year TEXT NOT NULL,
FOREIGN KEY (circuitid) REFERENCES CIRCUITS (circuitid),
PRIMARY KEY (raceid));

COPY RACES FROM 'C:\uni\8x\ATD\archive\races_modified.csv' DELIMITER ',' CSV HEADER;

CREATE TABLE DRIVER_STANDINGS (
raceid INT NOT NULL,
driver_id INT NOT NULL,
points INT NOT NULL,
FOREIGN KEY (raceid) REFERENCES RACES (raceid),
PRIMARY KEY(driverid,raceid));
COPY RESULTS FROM 'C:\uni\8x\ATD\archive\driver_standings_modified.csv' DELIMITER ',' CSV HEADER;


COPY (
    SELECT * FROM CIRCUITS NATURAL JOIN RACES NATURAL JOIN RESULTS
) TO 'C:\uni\8x\ATD\archive\NATURALJOINTABLE.csv' DELIMITER ',' CSV HEADER;