/*
SELECT * FROM CIRCUITS_MODIFIED NATURAL JOIN RACES_MODIFIED NATURAL JOIN DRIVER_STANDINGS_MODIFIED;

SELECT * FROM UNIVERSAL;
*/

SELECT * FROM CIRCUITS_MODIFIED NATURAL JOIN RACES_MODIFIED NATURAL JOIN DRIVER_STANDINGS_MODIFIED;
