DROP TABLE IF EXISTS NJ;
DROP TABLE IF EXISTS UNIVERSAL;
DROP TABLE IF EXISTS DRIVER_STANDINGS_MODIFIED;
DROP TABLE IF EXISTS RACES_MODIFIED;
DROP TABLE IF EXISTS CIRCUITS_MODIFIED;
DROP TABLE IF EXISTS DRIVER_STANDINGS CASCADE;
DROP TABLE IF EXISTS RACES CASCADE;
DROP TABLE IF EXISTS CIRCUITS CASCADE;

CREATE TABLE UNIVERSAL (
    raceId INT NOT NULL,
    year INT NOT NULL,
    driverId INT NOT NULL,
    points REAL NOT NULL,
    circuitId INT NOT NULL,
    alt INT NOT NULL
);

COPY UNIVERSAL FROM 'C:\uni\8x\ATD\F1Analysis\Exercise1\UNIVERSAL.csv' DELIMITER ',' CSV HEADER;

SELECT * FROM UNIVERSAL;